### ISSUE TITLE
Implement GZIP support

### ISSUE THREAD

**Issue by dmitrijsc** [harveysburger/pinnaclewrapper#1]
Hi there

I have just noticed that your solution does not use GZIP/ Deflate. How about to implement it to reduce the amount of traffic sent over network?

Solution: http://stackoverflow.com/questions/20990601/decompressing-gzip-stream-from-httpclient-response

Thanks!
Dmitry

**Comment by harveysburger** [comment]
Thanks for the suggestion. This will be included in the next version. 
Better late than never!
