### ISSUE TITLE
Delay limitation per call

### ISSUE THREAD

**Issue by Eliakos** [harveysburger/pinnaclewrapper#12]
Hello,

Do we know the delay betwen each call we cna submit? because on the FAQ available here https://www.ps3838.com/static/index.php/en-us/help/api-user-guide-en-us#migration-to-getOdds-and-getFixtures, we have :

How often can I refresh your odds?
=> You are able to make calls for any changes to the feed every five (5) seconds.

But we also have : The following limitations must be observed per sport:

- Requests made for the /fixtures and /odds operation without the since parameter must be restricted to once every 60 seconds;

- Requests made for the /fixtures and /odds operation with the since parameter must be restricted to once every 5 seconds.
=> i guess this must corresponds to the first rule above which does not mention it's with the since parameter 

Sorry, the subject is not really related to the wrapper but more on the logic and rules to respect

But then in the sample code app, should not we have delay to introduce between those lines ? :

                    var fixtures = await api.GetFixtures(new GetFixturesRequest(SampleSportId, lastFixture));

                    var lines = await api.GetOdds(new GetOddsRequest(fixtures.SportId,
                        fixtures.Leagues.Select(i => i.Id).ToList(), lastLine, false));

                    var leagues = await api.GetLeagues(SampleSportId);

**Comment by harveysburger** [comment]
Hey, sorry I am not sure of the specific rules on ps3838 side, or even pinnacle side for that matter.  If you call it too aggressively you'll get Api access revoked but I am not sure of the details. They won't block you if you run a few back to back calls like in the sample code there.

**Comment by Eliakos** [comment]
Thanks. In the context if automated betting, i suppose we should introduce a delay between the calls, what do you think of?
Anyway do you confirm there is actually no delay managment in the wrapper?
